include Makefile.inc

INCLUDES += -I$(MARTe2_DIR)/Lib/gtest-1.7.0/include

LIBRARIES   += ../../Build/$(TARGET)/Components/DataSources/DataSources$(LIBEXT)
LIBRARIES   += ../../Build/$(TARGET)/Components/DataSources/DataSourcesTests$(LIBEXT)
LIBRARIES   += ../../Build/$(TARGET)/Components/GAMs/GAMs$(LIBEXT)
LIBRARIES   += ../../Build/$(TARGET)/Components/Lib/DataSourceSignalChecker/DataSourceSignalChecker$(LIBEXT)
LIBRARIES   += ../../Build/$(TARGET)/Components/Lib/GAMSignalChecker/GAMSignalChecker$(LIBEXT)
LIBRARIES   += ../../Build/$(TARGET)/Components/Lib/SerialBuffer/SerialBuffer$(LIBEXT)
LIBRARIES   += ../../Build/$(TARGET)/Components/GAMs/GAMsTests$(LIBEXT)

LIBRARIES   += -L$(MARTe2_DIR)/Build/$(TARGET)/Core/ -lMARTe2
LIBRARIES   += $(MARTe2_DIR)/Lib/gtest-1.7.0/libgtest.a $(MARTe2_DIR)/Lib/gtest-1.7.0/libgtest_main.a
